// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );  
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACOu40p2L3cREImGDXfmrMG2h8joAk2f0',
    appId: '1:885045556191:web:fc9aa8e7684468792b0a6a',
    messagingSenderId: '885045556191',
    projectId: 'fypp-9065c',
    authDomain: 'fypp-9065c.firebaseapp.com',
    storageBucket: 'fypp-9065c.firebasestorage.app',
    measurementId: 'G-G79CW8Y8H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl0YAhK85FK3FFwZDjLNNnMl9II-iTpj8',
    appId: '1:885045556191:android:79870fa1234a2de42b0a6a',
    messagingSenderId: '885045556191',
    projectId: 'fypp-9065c',
    storageBucket: 'fypp-9065c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkAIF2uBxBtPSCSY4P3SH7iRdB0NVViq8',
    appId: '1:885045556191:ios:07398ce826ba78b62b0a6a',
    messagingSenderId: '885045556191',
    projectId: 'fypp-9065c',
    storageBucket: 'fypp-9065c.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkAIF2uBxBtPSCSY4P3SH7iRdB0NVViq8',
    appId: '1:885045556191:ios:07398ce826ba78b62b0a6a',
    messagingSenderId: '885045556191',
    projectId: 'fypp-9065c',
    storageBucket: 'fypp-9065c.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACOu40p2L3cREImGDXfmrMG2h8joAk2f0',
    appId: '1:885045556191:web:6d26c6b50a9693242b0a6a',
    messagingSenderId: '885045556191',
    projectId: 'fypp-9065c',
    authDomain: 'fypp-9065c.firebaseapp.com',
    storageBucket: 'fypp-9065c.firebasestorage.app',
    measurementId: 'G-C2E30QX4J5',
  );
}